version: "3"

services:
  my-jekyll-container:
    image: my-ruby-env:latest # This is image which built in step 2
    container_name: local_jekyll
    environment:
      GEM_HOME: .gems
    restart: always
    tty: true
#    volumes:
#      - type: volume
#        source: .
#        target: /data
#        # nocopy has no equivalent in the short syntax:
#        volume:
#          nocopy: true
    volumes:
      - .:/app
    ports:
      - "4000:4000"
#networks:
#  my-network:
#    driver: bridge