sudo: required
services:
  - docker
addons:
   apt:
     sources:
       - git-core
     packages:
       - git
       - jq

cache:
  directories:
    - $HOME/.m2
    - $HOME/cache/

branches:
    except:    
        - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/

install:
  - TRAVIS_WORK_DIR="${PWD}/.."
  - ./_scripts/prepare_build_prod_and_run.sh --working-dir=${TRAVIS_WORK_DIR} --store-cache=$HOME/cache/_tmp --gems-cache=$HOME/cache/.gems

script:
  - ./_scripts/travis-verify-publish.sh --working-dir=${TRAVIS_WORK_DIR} --browser-test=chromeHeadless --chrome-driver-version=2.33

notifications:
  email:
    recipients:
      - arquillian-team@lists.jboss.org
